version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ec2-user/sistemas-solares-pacifico
hooks:
  BeforeInstall:
    - location: pipeline-scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: pipeline-scripts/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: pipeline-scripts/application_start.sh
      timeout: 300
      runas: ec2-user
